name: setup-java-runner
description: Setup Java runner
inputs:
  java-version:
    required: true
  gradle-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: oracle-actions/setup-java@v1
      with:
        release: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ inputs.gradle-version }}
